## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
og_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
og_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = og_df.drop(['EIN', 'NAME'], axis=1)


df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type_counts = df['APPLICATION_TYPE'].value_counts()
print(app_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 500
application_types_to_replace = app_type_counts[app_type_counts < cutoff].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_counts = df['CLASSIFICATION'].value_counts()
print(class_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1248        1
C6100        1
C1820        1
C1900        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1256        2
C1246        2
C1234        2
C1267        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 70
classifications_to_replace = class_counts[class_counts < cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      499
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummies = pd.get_dummies(df)

In [ ]:
# Split our preprocessed data into our features and target arrays
y = df_dummies['IS_SUCCESSFUL']
X = df_dummies.drop('IS_SUCCESSFUL', axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=X_train.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 80)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,621 (25.86 KB)

 Trainable params: 6,621 (25.86 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
# Train the model using the scaled training data
history = nn.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test_scaled, y_test)
)

Epoch 1/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5403 - val_accuracy: 0.7320 - val_loss: 0.5495
Epoch 2/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7302 - loss: 0.5471 - val_accuracy: 0.7311 - val_loss: 0.5514
Epoch 3/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7365 - loss: 0.5414 - val_accuracy: 0.7310 - val_loss: 0.5503
Epoch 4/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7353 - loss: 0.5420 - val_accuracy: 0.7312 - val_loss: 0.5507
Epoch 5/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7317 - loss: 0.5411 - val_accuracy: 0.7344 - val_loss: 0.5486
Epoch 6/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7353 - loss: 0.5400 - val_accuracy: 0.7293 - val_loss: 0.5529
Epoch 7/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7404 - loss: 0.5366 - val_accuracy: 0.7293 - val_loss: 0.5483
Epoch 8/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7389 - loss: 0.5370 - val_accuracy: 0.7286 - val_loss: 0.5515
Epoch 9/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7381 - loss: 0.5378 - val_accuracy: 0.7324 - val_loss: 0.5500
Epoch 10/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7406 - loss: 0.5324 - val_accuracy: 0.7266 - val_loss: 0.5507
Epoch 11/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7403 - loss: 0.5350 - val_accuracy: 0.7233 - val_loss: 0.5504
Epoch 12/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7384 - loss: 0.5355 - val_accuracy: 0.7317 - val_loss: 0.5513
Epoch 13/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7386 - loss: 0.5341 - val_accuracy: 0.7301 - val_loss: 0.5497
Epoch 14/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7346 - loss: 0.5380 - val_accuracy: 0.7312 - val_loss: 0.5491
Epoch 15/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7338 - loss: 0.5408 - val_accuracy: 0.7317 - val_loss: 0.5498
Epoch 16/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7473 - loss: 0.5292 - val_accuracy: 0.7297 - val_loss: 0.5520
Epoch 17/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7397 - loss: 0.5362 - val_accuracy: 0.7254 - val_loss: 0.5495
Epoch 18/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7360 - loss: 0.5380 - val_accuracy: 0.7268 - val_loss: 0.5517
Epoch 19/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7354 - loss: 0.5420 - val_accuracy: 0.7336 - val_loss: 0.5508
Epoch 20/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7394 - loss: 0.5345 - val_accuracy: 0.7321 - val_loss: 0.5489
Epoch 21/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7412 - loss: 0.5357 - val_accuracy: 0.7322 - val_loss: 0.5509
Epoch 22/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7479 - loss: 0.5242 - val_accuracy: 0.7302 - val_loss: 0.5502
Epoch 23/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7413 - loss: 0.5350 - val_accuracy: 0.7299 - val_loss: 0.5507
Epoch 24/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7460 - loss: 0.5319 - val_accuracy: 0.7290 - val_loss: 0.5528
Epoch 25/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7369 - loss: 0.5399 - val_accuracy: 0.7324 - val_loss: 0.5508
Epoch 26/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7423 - loss: 0.5311 - val_accuracy: 0.7303 - val_loss: 0.5509
Epoch 27/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7391 - loss: 0.5368 - val_accuracy: 0.7322 - val_loss: 0.5491
Epoch 28/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7352 - loss: 0.5391 - val_accuracy: 0.7297 - val_loss: 0.5528
Epoch 29/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7468 - loss: 0.5296 - val_accuracy: 0.7294 - val_loss: 0.5521
Epoch 30/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7460 - loss: 0.5270 - val_accuracy: 0.7292 - val_loss: 0.5518
Epoch 31/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7387 - loss: 0.5328 - val_accuracy: 0.7329 - val_loss: 0.5519
Epoch 32/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5372 - val_accuracy: 0.7262 - val_loss: 0.5513
Epoch 33/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7456 - loss: 0.5315 - val_accuracy: 0.7312 - val_loss: 0.5523
Epoch 34/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7423 - loss: 0.5330 - val_accuracy: 0.7274 - val_loss: 0.5524
Epoch 35/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7380 - loss: 0.5363 - val_accuracy: 0.7309 - val_loss: 0.5510
Epoch 36/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7394 - loss: 0.5326 - val_accuracy: 0.7286 - val_loss: 0.5533
Epoch 37/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7441 - loss: 0.5308 - val_accuracy: 0.7283 - val_loss: 0.5531
Epoch 38/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7413 - loss: 0.5292 - val_accuracy: 0.7310 - val_loss: 0.5524
Epoch 39/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7393 - loss: 0.5351 - val_accuracy: 0.7319 - val_loss: 0.5558
Epoch 40/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7478 - loss: 0.5257 - val_accuracy: 0.7293 - val_loss: 0.5530
Epoch 41/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7404 - loss: 0.5336 - val_accuracy: 0.7311 - val_loss: 0.5520
Epoch 42/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7380 - loss: 0.5339 - val_accuracy: 0.7282 - val_loss: 0.5517
Epoch 43/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7403 - loss: 0.5342 - val_accuracy: 0.7293 - val_loss: 0.5549
Epoch 44/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7428 - loss: 0.5320 - val_accuracy: 0.7311 - val_loss: 0.5532
Epoch 45/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7419 - loss: 0.5321 - val_accuracy: 0.7271 - val_loss: 0.5535
Epoch 46/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7433 - loss: 0.5282 - val_accuracy: 0.7294 - val_loss: 0.5537
Epoch 47/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7402 - loss: 0.5353 - val_accuracy: 0.7305 - val_loss: 0.5521
Epoch 48/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7447 - loss: 0.5272 - val_accuracy: 0.7267 - val_loss: 0.5534
Epoch 49/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7424 - loss: 0.5307 - val_accuracy: 0.7280 - val_loss: 0.5528
Epoch 50/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7369 - loss: 0.5359 - val_accuracy: 0.7275 - val_loss: 0.5545
Epoch 51/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7407 - loss: 0.5337 - val_accuracy: 0.7306 - val_loss: 0.5561
Epoch 52/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7444 - loss: 0.5278 - val_accuracy: 0.7288 - val_loss: 0.5550
Epoch 53/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7474 - loss: 0.5265 - val_accuracy: 0.7259 - val_loss: 0.5551
Epoch 54/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7400 - loss: 0.5347 - val_accuracy: 0.7309 - val_loss: 0.5523
Epoch 55/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7438 - loss: 0.5291 - val_accuracy: 0.7301 - val_loss: 0.5544
Epoch 56/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7406 - loss: 0.5336 - val_accuracy: 0.7306 - val_loss: 0.5550
Epoch 57/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7435 - loss: 0.5274 - val_accuracy: 0.7287 - val_loss: 0.5556
Epoch 58/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7432 - loss: 0.5272 - val_accuracy: 0.7287 - val_loss: 0.5562
Epoch 59/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7417 - loss: 0.5309 - val_accuracy: 0.7282 - val_loss: 0.5541
Epoch 60/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7386 - loss: 0.5338 - val_accuracy: 0.7282 - val_loss: 0.5575
Epoch 61/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7404 - loss: 0.5332 - val_accuracy: 0.7282 - val_loss: 0.5573
Epoch 62/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7448 - loss: 0.5269 - val_accuracy: 0.7290 - val_loss: 0.5554
Epoch 63/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7411 - loss: 0.5300 - val_accuracy: 0.7292 - val_loss: 0.5567
Epoch 64/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7451 - loss: 0.5264 - val_accuracy: 0.7264 - val_loss: 0.5585
Epoch 65/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7477 - loss: 0.5267 - val_accuracy: 0.7289 - val_loss: 0.5561
Epoch 66/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7452 - loss: 0.5251 - val_accuracy: 0.7298 - val_loss: 0.5567
Epoch 67/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7421 - loss: 0.5294 - val_accuracy: 0.7285 - val_loss: 0.5581
Epoch 68/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7403 - loss: 0.5333 - val_accuracy: 0.7293 - val_loss: 0.5571
Epoch 69/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7412 - loss: 0.5323 - val_accuracy: 0.7287 - val_loss: 0.5554
Epoch 70/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7443 - loss: 0.5260 - val_accuracy: 0.7275 - val_loss: 0.5575
Epoch 71/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7423 - loss: 0.5282 - val_accuracy: 0.7289 - val_loss: 0.5569
Epoch 72/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7425 - loss: 0.5274 - val_accuracy: 0.7288 - val_loss: 0.5573
Epoch 73/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7431 - loss: 0.5270 - val_accuracy: 0.7267 - val_loss: 0.5583
Epoch 74/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7418 - loss: 0.5296 - val_accuracy: 0.7285 - val_loss: 0.5579
Epoch 75/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7389 - loss: 0.5340 - val_accuracy: 0.7279 - val_loss: 0.5595
Epoch 76/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7437 - loss: 0.5307 - val_accuracy: 0.7293 - val_loss: 0.5568
Epoch 77/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7414 - loss: 0.5324 - val_accuracy: 0.7278 - val_loss: 0.5569
Epoch 78/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7393 - loss: 0.5298 - val_accuracy: 0.7288 - val_loss: 0.5612
Epoch 79/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7404 - loss: 0.5289 - val_accuracy: 0.7307 - val_loss: 0.5578
Epoch 80/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7446 - loss: 0.5239 - val_accuracy: 0.7266 - val_loss: 0.5588
Epoch 81/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7408 - loss: 0.5306 - val_accuracy: 0.7279 - val_loss: 0.5577
Epoch 82/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7434 - loss: 0.5281 - val_accuracy: 0.7300 - val_loss: 0.5590
Epoch 83/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7399 - loss: 0.5294 - val_accuracy: 0.7289 - val_loss: 0.5581
Epoch 84/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7384 - loss: 0.5319 - val_accuracy: 0.7278 - val_loss: 0.5592
Epoch 85/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7437 - loss: 0.5265 - val_accuracy: 0.7294 - val_loss: 0.5602
Epoch 86/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7438 - loss: 0.5255 - val_accuracy: 0.7284 - val_loss: 0.5579
Epoch 87/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7433 - loss: 0.5292 - val_accuracy: 0.7271 - val_loss: 0.5618
Epoch 88/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7427 - loss: 0.5279 - val_accuracy: 0.7298 - val_loss: 0.5593
Epoch 89/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7460 - loss: 0.5236 - val_accuracy: 0.7287 - val_loss: 0.5596
Epoch 90/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7437 - loss: 0.5276 - val_accuracy: 0.7293 - val_loss: 0.5601
Epoch 91/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7431 - loss: 0.5253 - val_accuracy: 0.7272 - val_loss: 0.5578
Epoch 92/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7422 - loss: 0.5317 - val_accuracy: 0.7293 - val_loss: 0.5609
Epoch 93/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7436 - loss: 0.5234 - val_accuracy: 0.7277 - val_loss: 0.5619
Epoch 94/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7388 - loss: 0.5321 - val_accuracy: 0.7295 - val_loss: 0.5602
Epoch 95/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7403 - loss: 0.5308 - val_accuracy: 0.7299 - val_loss: 0.5600
Epoch 96/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7462 - loss: 0.5233 - val_accuracy: 0.7274 - val_loss: 0.5593
Epoch 97/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7414 - loss: 0.5265 - val_accuracy: 0.7286 - val_loss: 0.5613
Epoch 98/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7461 - loss: 0.5249 - val_accuracy: 0.7286 - val_loss: 0.5607
Epoch 99/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7482 - loss: 0.5239 - val_accuracy: 0.7284 - val_loss: 0.5623
Epoch 100/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7444 - loss: 0.5226 - val_accuracy: 0.7285 - val_loss: 0.5613

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 1s - 2ms/step - accuracy: 0.7285 - loss: 0.5613
Loss: 0.5612677931785583, Accuracy: 0.7284742593765259

In [ ]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.